services:
  postgres:
    image: postgres:latest
    container_name: bookstore
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1511
      POSTGRES_DB: bookstore
    volumes:
      - postgres_data:/var/lib/postgresql/bookstore

volumes:
  postgres_data: